### PR TITLE
chore: add Dockerfile

### PR DESCRIPTION
**Pull request by JangoCCC**

### CODE REVIEW

**Comment by eigmax** [comment]
We will remove the stated from this report, so ignore the diesel. @JangoCCC

**Comment by JangoCCC** [comment]
> We will remove the StateDb from this Repo, so ignore the diesel. @JangoCCC

So we don't need the postgres database either?

**Comment by eigmax** [comment]
Yes! We'll use another kind of database to store account state and scheduler state. Cc @BC-A @captainlee1024

**Comment by JangoCCC** [comment]
Note: env var DATABASE_URL is still needed for statedb, which is not set in the docker file. But as mentioned above, we will remove the statedb in the future.

**Pull request merged**
